name: Deploy pages
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build -- --base managed_explanation/
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
